"""Train Gaussian radial basis regression and export weights for C++.

Only the standard library is needed. Fixed Gaussian features feed a learned
linear output. Fit sqrt(density), then square predictions for nonnegativity.
This approximates known 1s physics; it is not a new solver or a speedup.
"""
import math
import argparse
from pathlib import Path
from generate_training_data import radial_density, samples

CENTERS = [-0.5 + 0.5 * i for i in range(27)]
WIDTH = 0.65
MAXIMUM = 12.0


def features(radius):
    return [math.exp(-((radius - center) / WIDTH) ** 2) for center in CENTERS]


def solve(matrix, target):
    """Solve the small ridge regression system with partial pivoting."""
    rows = [row[:] + [value] for row, value in zip(matrix, target)]
    size = len(rows)
    for column in range(size):
        pivot = max(range(column, size), key=lambda i: abs(rows[i][column]))
        rows[column], rows[pivot] = rows[pivot], rows[column]
        divisor = rows[column][column]
        if abs(divisor) < 1e-14:
            raise ValueError("Singular regression system")
        rows[column] = [value / divisor for value in rows[column]]
        for index in range(size):
            if index != column:
                factor = rows[index][column]
                rows[index] = [a - factor * b for a, b in zip(rows[index], rows[column])]
    return [row[-1] for row in rows]


def train():
    size = len(CENTERS)
    matrix = [[0.0] * size for _ in range(size)]
    target = [0.0] * size
    for radius, density in samples():
        values = features(radius)
        for i in range(size):
            target[i] += values[i] * math.sqrt(density)
            for j in range(size):
                matrix[i][j] += values[i] * values[j]
    for i in range(size):
        matrix[i][i] += 1e-8
    return solve(matrix, target)


def predict(radius, weights):
    amplitude = sum(v * w for v, w in zip(features(radius), weights))
    return amplitude * amplitude


def validate(weights):
    # Midpoints are held out from training. Volume weighting detects tail error.
    radii = [MAXIMUM * (i + 0.5) / 1200 for i in range(1200)]
    errors = [abs(predict(r, weights) - radial_density(r)) for r in radii]
    weighted = sum(r * r * e for r, e in zip(radii, errors)) / sum(
        r * r * radial_density(r) for r in radii)
    print(f"Held out maximum density error: {max(errors):.8f}")
    print(f"Held out radial weighted relative L1 error: {weighted:.6%}")
    if max(errors) > 0.01 or weighted > 0.01:
        raise ValueError("Model accuracy is below the export threshold")


def export(weights):
    output = Path(__file__).resolve().parents[1] / "src" / "LearnedDensityWeights.hpp"
    def values(items):
        return ",\n    ".join(f"{v:.17e}" for v in items)
    output.write_text(
        "// Generated by ml/train_model.py.\n#pragma once\n#include <array>\n"
        "namespace learned_density {\n"
        f"inline constexpr double width = {WIDTH};\n"
        f"inline constexpr double maximumRadius = {MAXIMUM};\n"
        f"inline constexpr std::array<double, {len(CENTERS)}> centers {{{{\n    {values(CENTERS)}\n}}}};\n"
        f"inline constexpr std::array<double, {len(weights)}> weights {{{{\n    {values(weights)}\n}}}};\n"
        "}\n", encoding="utf-8")
    print(f"Exported {output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate training without exporting")
    args = parser.parse_args()
    model = train()
    validate(model)
    if not args.check:
        export(model)
