"""Train Gaussian radial basis regression and export weights for C++.

PyTorch fits the output weights on CPU. Fixed Gaussian features feed a learned
linear output. Fit sqrt(density), then square predictions for nonnegativity.
This approximates known 1s physics; it is not a new solver or a speedup.
"""
import math
import torch
import argparse
from pathlib import Path
from generate_training_data import radial_density, samples

CENTERS = [-0.5 + 0.5 * i for i in range(27)]
WIDTH = 0.65
MAXIMUM = 12.0


def features(radius):
    return [math.exp(-((radius - center) / WIDTH) ** 2) for center in CENTERS]


def train():
    """Fit ridge regression with PyTorch tensors in double precision on CPU."""
    data = torch.tensor(samples(), dtype=torch.float64)
    radii = data[:, 0:1]
    centers = torch.tensor(CENTERS, dtype=torch.float64)
    design = torch.exp(-((radii - centers) / WIDTH).square())
    target = data[:, 1].sqrt()
    regularizer = 1e-8 * torch.eye(len(CENTERS), dtype=torch.float64)
    weights = torch.linalg.solve(design.T @ design + regularizer, design.T @ target)
    if not torch.isfinite(weights).all():
        raise ValueError("Training produced invalid weights")
    return weights.tolist()


def predict(radius, weights):
    amplitude = sum(v * w for v, w in zip(features(radius), weights))
    return amplitude * amplitude


def validate(weights):
    # Midpoints are held out from training. Volume weighting detects tail error.
    radii = [MAXIMUM * (i + 0.5) / 1200 for i in range(1200)]
    errors = [abs(predict(r, weights) - radial_density(r)) for r in radii]
    weighted = sum(r * r * e for r, e in zip(radii, errors)) / sum(
        r * r * radial_density(r) for r in radii)
    print(f"Held out maximum density error: {max(errors):.8f}")
    print(f"Held out radial weighted relative L1 error: {weighted:.6%}")
    if max(errors) > 0.01 or weighted > 0.01:
        raise ValueError("Model accuracy is below the export threshold")


def export(weights):
    output = Path(__file__).resolve().parents[1] / "src" / "LearnedDensityWeights.hpp"
    def values(items):
        return ",\n    ".join(f"{v:.17e}" for v in items)
    output.write_text(
        "// Generated by ml/train_model.py.\n#pragma once\n#include <array>\n"
        "namespace learned_density {\n"
        f"inline constexpr double width = {WIDTH};\n"
        f"inline constexpr double maximumRadius = {MAXIMUM};\n"
        f"inline constexpr std::array<double, {len(CENTERS)}> centers {{{{\n    {values(CENTERS)}\n}}}};\n"
        f"inline constexpr std::array<double, {len(weights)}> weights {{{{\n    {values(weights)}\n}}}};\n"
        "}\n", encoding="utf-8")
    print(f"Exported {output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Validate training without exporting")
    args = parser.parse_args()
    model = train()
    validate(model)
    if not args.check:
        export(model)
